[package]
name = "analytics-rust"
version = "0.1.0"
authors = ["Dean Karn <dean.karn@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"

[dependencies]
