[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"
edition = "2018"
license = "MIT"
name = "analytics"
version = "0.1.0"

[dependencies]
chrono = "0.4.6"
failure = "0.1.5"
serde_json = "1.0.39"
url = "1.7.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.93"

[dependencies.uuid]
features = [
    "serde",
    "v4",
]
version = "0.7.4"
