[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"
edition = "2018"
license = "MIT"
name = "analytics"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
serde = "1.0.93"
serde_json = "1.0.39"
uuid = { version = "0.7.4",  features = ["serde", "v4"]}
