[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"
edition = "2018"
license = "MIT"
name = "analytics"
version = "0.1.0"

[[bin]]
name = "analytics"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["clap"]

[dependencies]
base64 = "0.10"
failure = "0.1.5"
reqwest = "0.9"
serde = "1.0.93"
serde_json = { version = "1.0.39", features = ["raw_value"] }

clap = { version = "2.33", optional = true }
