[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Segment analytics client for Rust https://segment.com/docs/libraries/rust"
edition = "2018"
license = "MIT"
name = "analytics"
version = "0.1.0"

[[bin]]
name = "analytics"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["clap"]

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
serde_json = "1.0.39"
url = "1.7.2"
base64 = "0.10"
failure = "0.1.5"
reqwest = "0.9"
clap = { version = "2.33", optional = true }

[dependencies.serde]
features = ["derive"]
version = "1.0.93"

[dependencies.uuid]
features = [
    "serde",
    "v4",
]
version = "0.7.4"
